### ISSUE TITLE
Website resizes poorly

### ISSUE THREAD

**Issue by florence** [crew/website#17]
The website doesn't resize well. About 10% is cut off when I half screen it on my (1920X1080) monitor. the "other stuff" box and (more importantly) the caption on the banner becomes partially obscured.

**Comment by pranav** [comment]
Screenshot?

**Comment by florence** [comment]
![shot](https://f.cloud.github.com/assets/1413610/247211/c230b526-8acc-11e2-9307-2848f6c8d3ff.png)

Screenshotted

**Comment by pranav** [comment]
Get a bigger monitor?

**Comment by ali** [comment]
@pranav :+1:

**Comment by alekhinen** [comment]
I only made it to where the scaling started when screen-width was <= 720 px. I'll fix it so the layout is elastic at any screen res.

**Comment by pranav** [comment]
Fixed with the last few pull requests.
