### ISSUE TITLE
Get a list of projects and summaries

### ISSUE THREAD

**Issue by ali** [crew/website#8]

**Comment by pranav** [comment]
Crewtinuous Development, Crewu, Learnyou a linux, learn you a webdev, dds, metrics

**Comment by Jw0x47** [comment]
CrewU: Comes in 4 parts.
Linux: Basics (learn you a linux)
Linux: Advanced (fix your linux)
Linux: Infrastructure (build you a linux)
Webdev

**Comment by florence** [comment]
![crewprojects](https://f.cloud.github.com/assets/515861/324840/243cfa6c-9af5-11e2-8356-cb817638900a.jpg)

This is a list of all (known) project that occurred this semester. Any project with an arrow is one that still has work to be done. (There are some arrow missing. For example I dont think anyone wrote docs on our puppet configs).

**Comment by florence** [comment]
CrewU: Open source ware designed to get freshmen up to speed with the linux, systems, and web development skills Crew members need.

Metrics: A software suite designed to collect usage data from the WVH lab.

**Comment by ali** [comment]
Website
- Our website is a project created and maintained by new Crew members as a way to improve their web development and design skills.

Project Hosting
- Project Hosting in an initiative to get CCIS off of using SVN and Trac and on to Git.

IRC
- We manage our college's IRC server, used by students, organizations, and faculty.
